# Site setings
name: Yehonathan Sharvit
description: Developer. Author. Speaker.
meta_description: Data-Oriented programming. Simplicity. Interactive code snippets. Clojure.
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: authorimage.jpg
  greetings: Hi there! My name is Yehonathan Sharvit. I'm a software developer, author and speaker. My passion is to make interesting things easy to understand. I hope you will enjoy the articles.
favicon: assets/favicon2.png
baseurl: 
production_url: https://blog.klipse.tech
tinyletter_url: https://tinyletter.com/klipse
# Add your GA Tracking Id
ga_analytics: UA-75651930-1
# Contact form setings
email: viebel@gmail.com
contact_page_description: I am available remotely for mentoring developers, giving tech talks and conducting workshops about Data-Oriented Programming and Clojure. Let's be in touch!
thankyou_page_description: Your message has been successfully sent. We will contact you very soon!

formspree_id: xwkwjvne 
# Social links
twitter: viebel
linkedin: viebel

# Navigation
navigation:
  - text: Blog
    url: /
  - text: Talks
    url: /talks
  - text: About
    url: /about
  - text: Contact
    url: /contact
  - text: Search
    url: /search
  - text: Testimonials
    url: /testimonials

# Required Plugins
plugins_dir:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-asciidoc

asciidoctor:
  attributes:
    imagesdir:  /assets
    source-highlighter: pygments
    pygments-css: class
    pygments-stylesheet: css/asciidoc-pygments.css
# Pagination
paginate: 10
paginate_path: /page:num/

# Permalinks
#permalink: /:title

# Other
highlighter: rouge

# Sass
sass:
  sass_dir: _sass
  style: compressed
