skinparam object {
 ArrowColor DarkOliveGreen
 BackgroundColor White
 BorderColor CornflowerBlue
}

skinparam class {
 ArrowColor DarkOliveGreen
 BackgroundColor White
 BorderColor CornflowerBlue
}

skinparam nodesep 90
