= Principles of Data Oriented Programming
:page-layout: post
:page-description:  Data Oriented Programming in a nutshell. Benefits and drawbacks of data oriented programming. DO vs OOP. DO vs FP.
:page-categories: clojure
:page-guid: D964C45D-5CD0-409E-BBAC-60AAB0CA0FB7
:page-thumbnail: assets/klipse.png
:page-liquid:
:page-author: Yehonathan Sharvit
:page-date:   2020-09-29 05:31:24 +0200

++++
{% include databook-intro.html %}
++++

This chapter is an attempt to illustrate what are the core principles of Data Oriented Programming as I understand them.
It is highly influenced by my programming experience in Clojure, but I believe that those principles are language agnostic.

One could adhere to them in an Object Oriented (OO) language like Java or C# and one could break them
in a Functional Programming (FP) language like Ocaml, Haskell, JavaScript (or even in Clojure).

In fact, in this chapter, I am going to illustrate how those principles could be applied or broken
in JavaScript, a programming language that supports both FP and OOP.


The principles of Data Oriented (DO) Programming are:

. link:{% post_url 2020-10-02-separate-code-data %}[Separate code from data]
. link:{% post_url 2020-10-02-generic-data-structures %}[Model entities with generic data structures]
. link:{% post_url 2020-10-02-immutable-data %}[Data is immutable]
. link:{% post_url 2020-10-03-data-comparable-value %}[Data is comparable by value]
. link:{% post_url 2020-10-03-data-literal %}[Data has a literal representation]


Each principle is explored in a separate article.

I encourage you to start your exploration from link:{% post_url 2020-10-02-separate-code-data %}[Principle #1: Separate code from data].

Enjoy!

++++
{% include databook-intro.html %}
++++
